### ISSUE TITLE
Struct Values Assignment

### ISSUE THREAD

**Issue by raul5660** [mattifestation/PSReflect#7]
I may be just over looking something but how would i go about assigning values to a struct?

**Comment by mattifestation** [comment]
Once you create the struct type, just instantiate an instance and assign properties unless there's a portion of your question that I'm missing.

```powershell
$Mod = New-InMemoryModule -ModuleName Test

$SampleStructType = struct $Mod TestStruct @{
    Field0 = field 0 UInt16
    Field1 = field 1 UInt16
    Field2 = field 2 UInt32
    Field3 = field 3 UInt32
    Field4 = field 4 UInt32
    Field5 = field 5 UInt16
}

$SampleStructInstance = New-Object -TypeName TestStruct
$SampleStructInstance.Field0 = 1
```

**Comment by raul5660** [comment]
has this been tested on PS version 2? Trying to work with LSA_Policy

`
Import-Module ".\PSReflect.psm1"
$Mod = New-InMemoryModule -ModuleName Win32

$LSA_OBJECT_ATTRIBUTES_TYPE = struct $Mod LSA_OBJECT_ATTRIBUTES @{
        Length                   = field 0 UInt32
        RootDirectory            = field 1 IntPtr
        ObjectName               = field 2 IntPtr
        Attributes               = field 3 UInt32
        SecurityDescriptor       = field 4 IntPtr
        SecurityQualityOfService = field 5 IntPtr
    }

	$LSA_OBJECT_ATTRIBUTE = New-Object -TypeName LSA_OBJECT_ATTRIBUTES;
	$LSA_OBJECT_ATTRIBUTE.Length = 0;
`

Tried it on v5 worked great but v2 no luck :/

**Comment by mattifestation** [comment]
Ah okay yeah. There's a quirk with v2 that prevents you from calling New-Object on types created with PSReflect. You have to use the Activator class to get an instance.

```powershell
$Mod = New-InMemoryModule -ModuleName Win32

$LSA_OBJECT_ATTRIBUTES_TYPE = struct $Mod LSA_OBJECT_ATTRIBUTES @{
Length = field 0 UInt32
RootDirectory = field 1 IntPtr
ObjectName = field 2 IntPtr
Attributes = field 3 UInt32
SecurityDescriptor = field 4 IntPtr
SecurityQualityOfService = field 5 IntPtr
}

$LSA_OBJECT_ATTRIBUTE = [Activator]::CreateInstance($LSA_OBJECT_ATTRIBUTES_TYPE)
$LSA_OBJECT_ATTRIBUTE.Length = 1
```

Let should do it. I hope that helps!

**Comment by raul5660** [comment]
Yes it helped a lot. I was reading the comments and saw something about GetSize. I tried using the method but get an error


$LSA_OBJECT_ATTRIBUTE = [Activator]::CreateInstance($LSA_OBJECT_ATTRIBUTES_TYPE);
$LSA_OBJECT_ATTRIBUTE.Length = $LSA_OBJECT_ATTRIBUTE.GetSize();


GetSize : Method invocation failed because [LSA_OBJECT_ATTRIBUTES] doesn't contain a method named 'GetSize'.
At C:\Users\Raul Martinez\Source\Repos\PowerExporter\PowerExporter\PowerExporter\PowerExporter.ps1:54 char:62
+ $LSA_OBJECT_ATTRIBUTE.Length = $LSA_OBJECT_ATTRIBUTE.GetSize <<<< ();
    + CategoryInfo          : InvalidOperation: (GetSize:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by mattifestation** [comment]
GetSize is a static method so you need to invoke it as one (w/ ::).

```powershell
$LSA_OBJECT_ATTRIBUTE = [Activator]::CreateInstance($LSA_OBJECT_ATTRIBUTES_TYPE)
$LSA_OBJECT_ATTRIBUTE.Length = $LSA_OBJECT_ATTRIBUTE::GetSize()
```

**Comment by raul5660** [comment]
Thank makes sense. Thank you very much 👍
